name: 'emo-bon data management google drive downloader'
description: 'download google drive spreadsheets from data management metadata'
inputs:
  x:
    description: 'x'
    required: true
    default: 'x'
outputs:
  fx:
    description: 'fx'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.x }}
